// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnzhiyuButton: typeof import('./src/components/anzhiyu-button.vue')['default']
    Controller: typeof import('./src/components/controller.vue')['default']
    Identification: typeof import('./src/components/identification.vue')['default']
    MainContent: typeof import('./src/components/main-content.vue')['default']
    MainTop: typeof import('./src/components/main-top.vue')['default']
    Tip: typeof import('./src/components/tip.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    Wind: typeof import('./src/components/wind.vue')['default']
  }
}
